'''
Assignment #5
1. Add / modify code ONLY between the marked areas (i.e. "Place code below") 
2. Run the associated test harness for a basic check on completeness. A successful run of the test cases does not guarantee accuracy or fulfillment of the requirements. Please do not submit your work if test cases fail.
3. To run unit tests simply use the below command after filling in all of the code:
    python 05_assignment.py
  
4. Unless explicitly stated, please do not import any additional libraries but feel free to use built-in Python packages
5. Submissions must be a Python file and not a notebook file (i.e *.ipynb)
6. Do not use global variables
'''


In [234]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import unittest
import requests
import json

In [237]:
def exercise01():
    df = pd.DataFrame(np.random.randint(0,100,size=(3, 4)), columns=['a', 'b', 'c', 'd'])  
    return df

In [238]:
exercise01()

a   b   c   d
0  51   6  69  54
1  95  52  70  78
2  60  55  24  29

In [239]:
def exercise02(a):
    array = np.array(a)    
    return array

In [240]:
mets = ['Alonso', 'Guillorme', 'Lindor', 'Escobar', 'Canha', 'Nimmo', 'Marte', 'Alvarez']
exercise02(mets)

array(['Alonso', 'Guillorme', 'Lindor', 'Escobar', 'Canha', 'Nimmo',
       'Marte', 'Alvarez'], dtype='<U9')

In [241]:
def exercise03(a):
    sum = np.sum(a)
    return sum

In [242]:
randnums= np.random.randint(1,101,5)
exercise03(randnums)

290

In [243]:
def exercise04(a):
    sum = np.sum(a[1])
    return sum

In [244]:
x = np.array([[1, 2, 3], [4, 5, 6]])
exercise04(x)

15

In [245]:
def exercise05(n):
    zeros =  np.zeros((n, n))    
    return zeros

In [246]:
exercise05(5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [247]:
def exercise06(n):
    ones =  np.ones((n, n))    
    return ones

In [248]:
exercise06(5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [249]:
def exercise07(sd,m,s):
    random_numbers = np.random.normal(loc=sd, scale=m, size=s)
    return random_numbers

In [250]:
exercise07(5, 5, 5)

array([14.51769859,  0.26848539, -6.86574997, -1.93308694,  7.82197101])

In [251]:
def exercise08():
    df = pd.read_csv("https://tinyurl.com/y63q7okz")
    row_count = len(df.index)
    avg_sq_ft = df['sq__ft'].mean() 
    df_zip_95670 = df.loc[df['zip'] == 95670]
    df_zip_not_95610 = df.loc[df['zip'] != 95610]
    return row_count, avg_sq_ft, df_zip_95670, df_zip_not_95610

In [252]:
exercise08()

(985,
 1314.9167512690356,
                                street            city    zip state  beds  \
 8     11150 TRINITY RIVER DR Unit 114  RANCHO CORDOVA  95670    CA     2   
 81                 10245 LOS PALOS DR  RANCHO CORDOVA  95670    CA     3   
 116          2010 PROMONTORY POINT LN      GOLD RIVER  95670    CA     2   
 178              10542 SILVERWOOD WAY  RANCHO CORDOVA  95670    CA     3   
 211                 2460 EL ROCCO WAY  RANCHO CORDOVA  95670    CA     3   
 217                 2219 EL CANTO CIR  RANCHO CORDOVA  95670    CA     4   
 279  11281 STANFORD COURT LN Unit 604      GOLD RIVER  95670    CA     0   
 284          2015 PROMONTORY POINT LN      GOLD RIVER  95670    CA     3   
 293                 3512 RAINSONG CIR  RANCHO CORDOVA  95670    CA     4   
 451                10949 SCOTSMAN WAY  RANCHO CORDOVA  95670    CA     5   
 489                   10629 BASIE WAY  RANCHO CORDOVA  95670    CA     4   
 493                    3253 ABOTO WAY  RANCHO CO

In [254]:
def exercise10(n):
    identity_matrix = np.identity(n=n)    
    return identity_matrix

In [255]:
exercise10(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

     '''
    Using NumPy, create a single dimension array, array_1d, of size n containing integers 0 to n-1
    Reshape the array. The reshaped array, array_reshaped, should be n/3 columns and 3 rows
    '''

In [266]:
def exercise11(n):
    array_1d = np.array(range(0,n))
    array_reshaped = np.reshape(array_1d, (3, int(n/3))) 
    return array_1d, array_reshaped

In [267]:
exercise11(4)

ValueError: cannot reshape array of size 4 into shape (3,1)

In [274]:
def exercise12(n):
    checkerboard_matrix = np.array([[(i+j)%2 for i in range(1,2*n+1)] for j in range(2*n)])
    return checkerboard_matrix

In [275]:
exercise12(3)

array([[1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1]])

In [276]:
def exercise13(n):
    '''
    Create a pandas Series, s, with n random integers between 0 and n, for n days starting from 1/1/2010 and plot the
    cumulative sum on a  chart. The data range should be an index. pd.date_range() may help. 
    
    '''
    s = pd.Series(range(0,n) , index =  pd.date_range(start = 1/1/2010, end = 12/1/2010, periods = n)
    
    return s

SyntaxError: invalid syntax (<ipython-input-276-f7a5a1c1e4c3>, line 9)

In [216]:
exercise13(3)

ValueError: Of the four parameters: start, end, periods, and freq, exactly three must be specified

In [286]:
exercise14(n):
    df = pd.DataFrame (words, columns = ['column_name'])
    return df

SyntaxError: invalid syntax (<ipython-input-286-7b4e77d2df6f>, line 1)

In [277]:
df = pd.read_csv("https://tinyurl.com/y63q7okz")
def exercise15():
    '''
    Use the real estate transaction DataFrame from Exercise 8 and extract into a new DataFrame every 5th row using iloc 
    and just the street address and zip code columns. This can be done with one line of code.
    '''
    df = df.iloc[::5, :]
    return df


In [278]:
exercise15()

UnboundLocalError: local variable 'df' referenced before assignment