Mathew Katz HW2

1. Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.

In [2]:
import numpy as np

In [83]:
a = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]])

In [84]:
def eigenme(a):
    w, v = np.linalg.eig(a) 
    print( "These are the Eigenvalues of the array given:",w)
    print( "These are the Eigenvectors of the array given:",v)

In [85]:
eigenme(m)

These are the Eigenvalues of the array given: [2. 1.]
These are the Eigenvectors of the array given: [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


---

2.  Write a Python program to compute the factor of a given array by Singular Value Decomposition


In [86]:
a = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]])

In [87]:
def sdpfac(array):
    U, s, V = np.linalg.svd(a)
    q, r = np.linalg.qr(a)
    print("Factor of a given array  by Singular Value Decomposition:")
    print("U=\n", U, "\ns=\n", s, "\nV=\n", V)

In [88]:
sdpfac(a)

Factor of a given array  by Singular Value Decomposition:
U=
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
 [3.         2.23606798 2.         0.        ] 
V=
 [[-0.          0.          1.          0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [-0.          1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]


---

3.  Write a Python program to compute the determinant of an array.


In [3]:
a = np.array([[1,2],[3,4]])

In [4]:
def det(a):
    determinant =  np.linalg.det(a)
    print("Determinant of the given array is:",determinant)



In [5]:
det(a)

Determinant of the given array is: -2.0000000000000004


---